---

- name: install setup tools
  package: name=python-setuptools state=present

- name: ensure cm config is removed
  file: path=/root/.cloudmonkey/config state=absent

- name: install cloudmonkey
  shell: easy_install cloudmonkey

- name: base configuration
  shell: cloudmonkey set history_file /usr/share/cloudmonkey_history && cloudmonkey set log_file /var/log/cloudmonkey && cloudmonkey set log_file /var/log/cloud-cli.log && cloudmonkey set username admin && cloudmonkey set password password
 
- name: download jq to parse json
  get_url: url=http://stedolan.github.io/jq/download/linux64/jq dest=/usr/bin mode=0777
